name: Delete quay image on PR closed
on:
  pull_request:
    branch: [main]
    types:
      - opened
      - closed

  workflow_dispatch: {}  #
env:
  QUAY_ODH_CAIKIT_TGIS_SERVING_IMAGE_REPO: ${{ secrets.QUAY_ODH_CAIKIT_TGIS_SERVING_IMAGE_REPO }}

jobs:
  delete-pr-quay-image:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Login to quay.io
        shell: bash
        env:
          QUAY_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
          QUAY_ROBOT_USERNAME: ${{ secrets.QUAY_ROBOT_USERNAME }}
          TEST: ${{ secrets.TEST }}
        run: |
         echo "$TEST2"
         docker login quay.io -u ${QUAY_ROBOT_USERNAME} -p ${QUAY_TOKEN}
      - name: Delete PR image
        shell: bash
        env:
          PR: ${{ github.event.pull_request.number }}
        run: |
          skopeo list-tags docker://${QUAY_ODH_CAIKIT_TGIS_SERVING_IMAGE_REPO}:pr-${PR}

